# Generated by Django 4.2.4 on 2023-08-11 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_profile_is_public"),
    ]

    operations = [
        migrations.CreateModel(
            name="Social",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="lionnic", max_length=100)),
                (
                    "social",
                    models.URLField(default="https://www.lionnic.com/", max_length=255),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile_social",
                        to="accounts.profile",
                    ),
                ),
            ],
        ),
    ]
